# Generated by Django 5.1.2 on 2024-10-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('contrasena', models.CharField(default='S/A', max_length=30)),
                ('correo', models.CharField(default='S/A', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(default='S/A', max_length=50)),
                ('edad', models.IntegerField()),
            ],
        ),
    ]
